### ISSUE TITLE
购买后不小心关闭了浏览器

### ISSUE THREAD

**Issue by chen9965** [MCYUNIDC/DDOS#1]
如题，如何恢复   7:30左右购买

**Comment by MCYUNIDC** [comment]
等我回到家了，看看吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月22日(周一) 晚上7:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [MCYUNIDC/MCYUN-DDoS] 购买后不小心关闭了浏览器 (Issue #1)




 
如题，如何恢复   7:30左右购买

**Comment by chen9965** [comment]
好的，谢谢你 这里是支付截图 
![微信图片_20240722193824](https://github.com/user-attachments/assets/0bfb7626-037b-4e5f-b15c-8ce5f05ca411)

**Comment by chen9965** [comment]
你好，处理完了吗

**Comment by MCYUNIDC** [comment]
还在外面



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月22日(周一) 晚上10:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MCYUNIDC/MCYUN-DDoS] 购买后不小心关闭了浏览器 (Issue #1)




 
你好，处理完了吗

**Comment by chen9965** [comment]
oh,那实在不行把钱退给我我重新购买一下吧，我微信号是XIAOCH114514

**Comment by MCYUNIDC** [comment]
我到家了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月22日(周一) 晚上10:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MCYUNIDC/MCYUN-DDoS] 购买后不小心关闭了浏览器 (Issue #1)




 
oh,那实在不行把钱退给我我重新购买一下吧，我微信号是XIAOCH114514
